name: artifacts.builder

on:
  workflow_call:
    outputs:
      run_id:
        description: "run id of builder workflow"
        value: ${{ github.run_id }}

env:
  SLN_PATH: .\Up2dateService\Up2dateService.sln
  ARTIFACTS_PATH_X32: .\Up2dateService\Setup32\Release\
  ARTIFACTS_PATH_X64: .\Up2dateService\Setup64\Release\

jobs:
  artifacts:
    name: Building artifacts
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: Install .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
      - uses: seanmiddleditch/gha-setup-vsdevenv@v4

      - uses: nuget/setup-nuget@v1

      - name: Disable Out of Process Building
        run: .\DisableOutOfProcBuild.exe
        working-directory: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild

      - name: Restore packages
        shell: cmd
        run: msbuild "%SLN_PATH%" /t:restore /p:RestorePackagesConfig=true

      - name: Build Setup.exe
        shell: cmd
        run: devenv "%SLN_PATH%" /build "Release"

      - name: Upload setup64.exe
        uses: actions/upload-artifact@v3
        with:
          name: setup64.exe
          path: ${{ env.ARTIFACTS_PATH_X64 }}\setup.exe

      - name: Upload Up2dateSetup64.msi
        uses: actions/upload-artifact@v3
        with:
          name: Up2dateSetup64.msi
          path: ${{ env.ARTIFACTS_PATH_X64 }}\Up2dateSetup64.msi

      - name: Upload setup32.exe
        uses: actions/upload-artifact@v3
        with:
          name: setup32.exe
          path: ${{ env.ARTIFACTS_PATH_X32 }}\setup.exe

      - name: Upload Up2dateSetup32.msi
        uses: actions/upload-artifact@v3
        with:
          name: Up2dateSetup32.msi
          path: ${{ env.ARTIFACTS_PATH_X32 }}\Up2dateSetup32.msi
