name: artifacts.builder

on:
  push:
    branches: [ 4-add-ci-pipeline ]
    tags:
      - "v*.*.*"
  workflow_dispatch:


jobs:
  build:
    uses: ./.github/workflows/build.yaml

  pre-release:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - run: echo ${{ needs.build.outputs.run_id }}

