name: artifacts.builder

on:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"
  workflow_dispatch:


jobs:
  build:
    uses: ./.github/workflows/build.yaml

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/release.yaml

